#
# $FreeBSD$
#

.include <bsd.own.mk>

SUBDIR= \
	libwapcaplet \
	libparserutils \
	libcss \
	libhubbub \
	libdom \
	libnsbmp \
	libnsgif \
	librosprite \
	libnsfb \
	libsvgtiny \
	nsfb

.include <bsd.subdir.mk>
